/*
 * This file is generated by jOOQ.
 */
package ru.panic.companyservice.generatedClasses.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.panic.companyservice.generatedClasses.tables.CompaniesTable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompaniesTableRecord extends UpdatableRecordImpl<CompaniesTableRecord> implements Record6<Long, String, String, String, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.companies_table.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.companies_table.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.companies_table.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.companies_table.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.companies_table.owner</code>.
     */
    public void setOwner(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.companies_table.owner</code>.
     */
    public String getOwner() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.companies_table.webhook_url</code>.
     */
    public void setWebhookUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.companies_table.webhook_url</code>.
     */
    public String getWebhookUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.companies_table.secret_key</code>.
     */
    public void setSecretKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.companies_table.secret_key</code>.
     */
    public String getSecretKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.companies_table.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.companies_table.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CompaniesTable.COMPANIES_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return CompaniesTable.COMPANIES_TABLE.COMPANY_NAME;
    }

    @Override
    public Field<String> field3() {
        return CompaniesTable.COMPANIES_TABLE.OWNER;
    }

    @Override
    public Field<String> field4() {
        return CompaniesTable.COMPANIES_TABLE.WEBHOOK_URL;
    }

    @Override
    public Field<String> field5() {
        return CompaniesTable.COMPANIES_TABLE.SECRET_KEY;
    }

    @Override
    public Field<Long> field6() {
        return CompaniesTable.COMPANIES_TABLE.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCompanyName();
    }

    @Override
    public String component3() {
        return getOwner();
    }

    @Override
    public String component4() {
        return getWebhookUrl();
    }

    @Override
    public String component5() {
        return getSecretKey();
    }

    @Override
    public Long component6() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCompanyName();
    }

    @Override
    public String value3() {
        return getOwner();
    }

    @Override
    public String value4() {
        return getWebhookUrl();
    }

    @Override
    public String value5() {
        return getSecretKey();
    }

    @Override
    public Long value6() {
        return getCreatedAt();
    }

    @Override
    public CompaniesTableRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CompaniesTableRecord value2(String value) {
        setCompanyName(value);
        return this;
    }

    @Override
    public CompaniesTableRecord value3(String value) {
        setOwner(value);
        return this;
    }

    @Override
    public CompaniesTableRecord value4(String value) {
        setWebhookUrl(value);
        return this;
    }

    @Override
    public CompaniesTableRecord value5(String value) {
        setSecretKey(value);
        return this;
    }

    @Override
    public CompaniesTableRecord value6(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CompaniesTableRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompaniesTableRecord
     */
    public CompaniesTableRecord() {
        super(CompaniesTable.COMPANIES_TABLE);
    }

    /**
     * Create a detached, initialised CompaniesTableRecord
     */
    public CompaniesTableRecord(Long id, String companyName, String owner, String webhookUrl, String secretKey, Long createdAt) {
        super(CompaniesTable.COMPANIES_TABLE);

        setId(id);
        setCompanyName(companyName);
        setOwner(owner);
        setWebhookUrl(webhookUrl);
        setSecretKey(secretKey);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
