/*
 * This file is generated by jOOQ.
 */
package ru.panic.withdrawalservice.generatedClasses;


import ru.panic.withdrawalservice.generatedClasses.tables.ClientsTable;
import ru.panic.withdrawalservice.generatedClasses.tables.CompaniesTable;
import ru.panic.withdrawalservice.generatedClasses.tables.FlywaySchemaHistory;
import ru.panic.withdrawalservice.generatedClasses.tables.PaymentsTable;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.clients_table</code>.
     */
    public static final ClientsTable CLIENTS_TABLE = ClientsTable.CLIENTS_TABLE;

    /**
     * The table <code>public.companies_table</code>.
     */
    public static final CompaniesTable COMPANIES_TABLE = CompaniesTable.COMPANIES_TABLE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.payments_table</code>.
     */
    public static final PaymentsTable PAYMENTS_TABLE = PaymentsTable.PAYMENTS_TABLE;
}
