/*
 * This file is generated by jOOQ.
 */
package ru.panic.managementpaymentservice.generatedClasses;


import ru.panic.managementpaymentservice.generatedClasses.tables.ClientsTable;
import ru.panic.managementpaymentservice.generatedClasses.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.clients_table</code>.
     */
    public static final ClientsTable CLIENTS_TABLE = ClientsTable.CLIENTS_TABLE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
